# Generated by Django 5.2.4 on 2025-07-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('want', 'Want to Read'), ('reading', 'Currently Reading'), ('finished', 'Finished'), ('abandoned', 'Abandoned'), ('rereading', 'Re-reading')], default='unread', max_length=10)),
                ('genre', models.CharField(blank=True, choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('SCIFI', 'Sci-Fi'), ('FAN', 'Fantasy'), ('BIO', 'Biography')], max_length=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
