# Generated by Django 5.2.4 on 2025-07-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('Aca', 'Academic'), ('JA', 'Journal Articles')], max_length=5, null=True),
        ),
    ]
