# Generated by Django 5.2.5 on 2025-08-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('want', 'Want to Read'), ('reading', 'Currently Reading'), ('finished', 'Finished'), ('abandoned', 'Abandoned'), ('rereading', 'Re-reading')], default='unread', max_length=10)),
                ('genre', models.CharField(blank=True, choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('ACA', 'Academic'), ('JA', 'Journal Articles'), ('BIO', 'Biography'), ('SCI', 'Science'), ('HIS', 'History')], max_length=5, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['-date_added'],
            },
        ),
    ]
